### PR TITLE
Aidan py tests for Xeff

### PR DESCRIPTION
**Pull request by MDKempe**
We added a pytest to do an Xeff calculation.

### CODE REVIEW

**Review by tobin-ford — APPROVED** [review]
Simple changes everything looks good. Docstring updates are inconsequential and all tests passing on old and new pytests. Pytest h5 file to gitignore this should be fine.

**Comment by tobin-ford** [comment]
Don't pull to main. Create new PR.

**Comment by martin-springer** [comment]
@tobin-ford  - I can re-open the PR and change the base.

**Comment by martin-springer** [comment]
once the tests are done, you can go ahead and merge it into development.

@MDKempe @AidanWesley  - Please always make pull requests into development, not into main. Thanks.

**Pull request merged**
